# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# asyncronous execution library (for deoplete)
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# snippet repository
[[plugins]]
repo = 'honza/vim-snippets'
