# save vim session (type :Obsession to save)
[[plugins]]
repo = 'tpope/vim-obsession'

# snippet expansion ('deoppet.nvim' which is improved version of
# 'neosnippet.vim' is comming soon!)
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['vim-snippets']
on_i = 1
