[[plugins]]
repo = "airblade/vim-gitgutter"
on_event = 'BufRead'
hook_add = '''
nnoremap [git] <Nop>
nmap <Leader>g [git]
nmap [git]hs <Plug>(GitGutterStageHunk)
nmap [git]hu <Plug>(GitGutterUndoHunk)
nmap [git]hp <Plug>(GitGutterPreviewHunk)
'''
hook_post_source = '''
set updatetime=300
'''

[[plugins]]
repo = "tpope/vim-fugitive"
on_event = 'CmdlineEnter'
hook_add = '''
nnoremap [git] <Nop>
nmap <Leader>g [git]
nmap <silent> [git]a :<C-u>Gwrite<CR>
nmap <silent> [git]b :<C-u>Gblame<CR>
nmap <silent> [git]c :<C-u>Gcommit<CR>
nmap <silent> [git]d :<C-u>Gvdiff<CR>
nmap <silent> [git]f :<C-u>Gfetch<CR>
nmap <silent> [git]g :<C-u>Ggrep
nmap <silent> [git]m :<C-u>Gmerge
nmap <silent> [git]p :<C-u>Gpush<CR>
nmap <silent> [git]r :<C-u>Grebase -i<CR>
nmap <silent> [git]s :<C-u>Gstatus<CR>
'''

[[plugins]]
repo = 'junegunn/gv.vim'
on_event = 'CmdlineEnter'
hook_add = '''
nnoremap [git] <Nop>
nmap <Leader>g [git]
nmap <silent> [git]la :<C-u>GV<CR>
nmap <silent> [git]lc :<C-u>GV!<CR>
'''

[[plugins]]
repo = 'tpope/vim-obsession'
on_event = ['CmdlineEnter']

[[plugins]]
repo = 'kannokanno/previm'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

