# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# color scheme
[[plugins]]
repo = 'flazz/vim-colorschemes'

# asyncronous execution library (for deoplete)
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
