# save vim session (type :Obsession to save)
[[plugins]]
repo = 'tpope/vim-obsession'

# syntax hilighting
[[plugins]]
repo = 'rcmdnk/vim-markdown'

#
[[plugins]]
repo = 'tyru/open-browser.vim'

# preview markdown
[[plugins]]
repo = 'kannokanno/previm'
