[[plugins]]
repo = 'tpope/vim-obsession'
on_event = ['CmdlineEnter']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

