[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> ot
  \ denite#do_map('do_action', 'tabopen')
  nnoremap <silent><buffer><expr> os
  \ denite#do_map('do_action', 'split')
  nnoremap <silent><buffer><expr> ov
  \ denite#do_map('do_action', 'vsplit')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

nnoremap [denite] <Nop>
nmap <Space>u [denite]
nmap <silent> [denite]b :<C-u>Denite buffer<CR>
nmap <silent> [denite]c :<C-u>Denite command<CR>
nmap <silent> [denite]f :<C-u>Denite file/rec<CR>
nmap <silent> [denite]g :<C-u>Denite grep<CR>
nmap <silent> [denite]* :<C-u>DeniteCursorWord grep<CR>
nmap <silent> [denite]l :<C-u>Denite line<CR>
nmap <silent> [denite]r :<C-u>Denite -resume<CR>
nmap <silent> [denite]<C-n> :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
nmap <silent> [denite]<C-p> :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
'''
hook_post_source = '''
" Change file/rec command.
call denite#custom#var('file/rec', 'command',
  \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
" Change sorters.
call denite#custom#source(
  \ 'file/rec', 'sorters', ['sorter/sublime'])
let s:menus.my_commands = {
  \ 'description': 'Example commands'
  \ }
let s:menus.my_commands.command_candidates = [
  \ ['Split the window', 'vnew'],
  \ ['Open zsh menu', 'Denite menu:zsh'],
  \ ['Format code', 'FormatCode', 'go,python'],
  \ ]
call denite#custom#var('menu', 'menus', s:menus)
" Ag command on grep source
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts',
  \ ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'tpope/vim-obsession'
on_event = ['CmdlineEnter']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'kannokanno/previm'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_event = ['CmdlineEnter']
on_ft = ['markdown', 'rrst', 'asciidoc']

